import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { NyraShell } from "@/components/nyra/NyraShell";
import { NyraOrb } from "@/components/nyra/NyraOrb";
import { NyraStatus } from "@/components/nyra/NyraStatus";
import { VoiceButton } from "@/components/nyra/VoiceButton";
import { ConversationPanel } from "@/components/nyra/ConversationPanel";
import { StatusPill } from "@/components/nyra/SystemStatus";
import { useNyra } from "@/hooks/useNyra";
import { getNyraStatus } from "@/lib/nyra/ai.functions";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Nyra — Your personal AI operating system" },
      {
        name: "description",
        content:
          "Nyra listens, understands, routes, acts and remembers. A calm, voice-first personal AI operating system.",
      },
      { property: "og:title", content: "Nyra — Your personal AI operating system" },
      {
        property: "og:description",
        content: "Speak. Think. Remember. Act. Nyra is a voice-first personal AI operating system.",
      },
    ],
  }),
  loader: () => getNyraStatus(),
  component: HomePage,
});

function greeting() {
  const h = new Date().getHours();
  if (h < 5) return "Still awake.";
  if (h < 12) return "Good morning.";
  if (h < 18) return "Good afternoon.";
  return "Good evening.";
}

function HomePage() {
  const status = Route.useLoaderData();
  const nyra = useNyra(status);
  const [hello, setHello] = useState("Hello.");

  useEffect(() => setHello(greeting()), []);

  return (
    <NyraShell>
      <div className="flex flex-col items-center gap-8 pt-6 sm:pt-10">
        <div className="text-center">
          <h1 className="text-3xl font-light tracking-tight sm:text-4xl">{hello}</h1>
          <p className="mt-2 text-muted-foreground">How can I help?</p>
        </div>

        <NyraOrb state={nyra.state} />

        <NyraStatus state={nyra.state} detail={nyra.error ?? undefined} />

        <VoiceButton
          state={nyra.state}
          disabled={!nyra.micSupported}
          onStart={() => void nyra.startListening()}
          onStop={() => {
            nyra.stopListening();
            nyra.stopSpeaking();
          }}
        />

        <div className="flex flex-wrap items-center justify-center gap-2">
          <StatusPill
            label="AI"
            ok={status.aiConfigured}
            okText={status.aiModel}
            offText="Not configured"
          />
          <StatusPill
            label="Voice"
            ok={status.ttsConfigured}
            okText="ElevenLabs ready"
            offText="Not configured"
          />
          <StatusPill
            label="Mic"
            ok={nyra.micSupported}
            okText="Ready"
            offText="Unsupported browser"
          />
          <StatusPill
            label="Isolation"
            ok={nyra.settings.voiceIsolation}
            okText="On"
            offText="Off"
          />
        </div>

        <ConversationPanel
          messages={nyra.messages}
          partial={nyra.partial}
          disabled={nyra.state === "processing"}
          onSend={(text) => void nyra.send(text)}
        />

        <p className="max-w-xl text-center text-xs leading-relaxed text-muted-foreground">
          Nyra only listens when you start a session. Audio is processed in your browser and never
          stored. Replies are generated by an external AI provider when configured.
        </p>
      </div>
    </NyraShell>
  );
}
