/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SocialRouteImport } from './routes/social'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ApiDevicesRouteImport } from './routes/api/devices'
import { Route as ApiDevicesIdRouteImport } from './routes/api/devices.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesRoute = ApiDevicesRouteImport.update({
  id: '/api/devices',
  path: '/api/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesIdRoute = ApiDevicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDevicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/devices': typeof DevicesRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/social': typeof SocialRoute
  '/tasks': typeof TasksRoute
  '/today': typeof TodayRoute
  '/api/devices': typeof ApiDevicesRouteWithChildren
  '/api/devices/$id': typeof ApiDevicesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/devices': typeof DevicesRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/social': typeof SocialRoute
  '/tasks': typeof TasksRoute
  '/today': typeof TodayRoute
  '/api/devices': typeof ApiDevicesRouteWithChildren
  '/api/devices/$id': typeof ApiDevicesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/auth': typeof AuthRoute
  '/devices': typeof DevicesRoute
  '/memory': typeof MemoryRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/social': typeof SocialRoute
  '/tasks': typeof TasksRoute
  '/today': typeof TodayRoute
  '/api/devices': typeof ApiDevicesRouteWithChildren
  '/api/devices/$id': typeof ApiDevicesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/auth'
    | '/devices'
    | '/memory'
    | '/settings'
    | '/skills'
    | '/social'
    | '/tasks'
    | '/today'
    | '/api/devices'
    | '/api/devices/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/auth'
    | '/devices'
    | '/memory'
    | '/settings'
    | '/skills'
    | '/social'
    | '/tasks'
    | '/today'
    | '/api/devices'
    | '/api/devices/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/auth'
    | '/devices'
    | '/memory'
    | '/settings'
    | '/skills'
    | '/social'
    | '/tasks'
    | '/today'
    | '/api/devices'
    | '/api/devices/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AuthRoute: typeof AuthRoute
  DevicesRoute: typeof DevicesRoute
  MemoryRoute: typeof MemoryRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  SocialRoute: typeof SocialRoute
  TasksRoute: typeof TasksRoute
  TodayRoute: typeof TodayRoute
  ApiDevicesRoute: typeof ApiDevicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices': {
      id: '/api/devices'
      path: '/api/devices'
      fullPath: '/api/devices'
      preLoaderRoute: typeof ApiDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/$id': {
      id: '/api/devices/$id'
      path: '/$id'
      fullPath: '/api/devices/$id'
      preLoaderRoute: typeof ApiDevicesIdRouteImport
      parentRoute: typeof ApiDevicesRoute
    }
  }
}

interface ApiDevicesRouteChildren {
  ApiDevicesIdRoute: typeof ApiDevicesIdRoute
}

const ApiDevicesRouteChildren: ApiDevicesRouteChildren = {
  ApiDevicesIdRoute: ApiDevicesIdRoute,
}

const ApiDevicesRouteWithChildren = ApiDevicesRoute._addFileChildren(
  ApiDevicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AuthRoute: AuthRoute,
  DevicesRoute: DevicesRoute,
  MemoryRoute: MemoryRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  SocialRoute: SocialRoute,
  TasksRoute: TasksRoute,
  TodayRoute: TodayRoute,
  ApiDevicesRoute: ApiDevicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
